apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-zerviez-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: web-zerviez
          image: peaceofsheep/web-zerviez:v0.0.1
          ports:
            - containerPort: 3000
