name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  GKE_CLUSTER: zerviez-cluster
  GKE_ZONE: us-west4-a
  ZERVIEZ_WEB_TAG: 0.1.0

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: Deploy
      run: |
        kubectl apply -f k8s
        kubectl set image deployments/web-zerviez-deployment web-zerviez=peaceofsheep/web-zerviez:$ZERVIEZ_WEB_TAG
